### ISSUE TITLE
[BUG] - recents do not populate on 0.0.4

### ISSUE THREAD

**Issue by andrewmeyer** [damontecres/StashAppAndroidTV#35]
### Description

It appears that the recent fields no longer populate in 0.0.4 and stash v0.24.1

### Reproduction steps

```bash
1. open the app
2. observe the recently added etc. sections, they should be empty
```

### Device

NVIDIA SHIELD

**Comment by damontecres** [comment]
Can you describe more what you mean?

Starting with `v0.0.3` in #22, the rows shown on the main screen are the same ones from the regular web UI of Stash instead of just showing recently added stuff. So if you mean those are gone, then that's intentional.

But if there is a title with no content (but the Web UI has content), then it's probably a bug. If so, there should have been a message shown shown that says a error occurred.

**Comment by andrewmeyer** [comment]
Sorry for the incomplete bug report.

Recently released scenes, studio, movies, and performers all have entries with metadata in stash, but the corresponding sections on the 0.0.4 app are all empty, even after a force stop and cache clear of the app.  Let me try rolling back to 0.0.3 later today and see if I can collect additional information - this was an upgrade from 0.0.2 to 0.0.4

**Comment by damontecres** [comment]
Might be an issue similar to #12 where I've speculated there's something in the results that isn't being parsed correctly causing an exception (which would result in an empty row).

**Comment by st0r4ge** [comment]
I do have the same issue, running v0.0.5 on an Nvidia Shield Pro. Stash is currently on v0.24.3 (I was on 0.24.1 before the latest update, the issue persisted across both versions).

Unlike the aforementioned issue #12 , my scene count is much lower, at around 1440 scenes.
I saw you merged #19  for better error handling. Is there any way I can now gather logs easily to help resolve this issue?

If not, I should also be able to collect logs using ADB.

**Comment by damontecres** [comment]
> Is there any way I can now gather logs easily to help resolve this issue?
> 
> If not, I should also be able to collect logs using ADB.

There's no way to gather logs in the app yet unfortunately, but you can definitely use ADB & [logcat](https://developer.android.com/tools/logcat). All of the exceptions for making network calls to the Stash server are logged. A good filter for logcat could be `adb logcat "Constants:V QueryEngine:V *:F"`. If nothing obvious, you can switch `*:F` to `*:E` (fatal to error).

Any additional info, especially logs, would be very helpful in debugging this!

**Comment by st0r4ge** [comment]
@damontecres  Ok. So i connected via ADB. Forced Stopped the Application and startet logging with the first provided command. This is the output when starting the Application and Browsing Perfomers and Scene:

```
C:\Users\Jake>adb logcat "Constants:V QueryEngine:V *:F
--------- beginning of system
--------- beginning of main
01-15 21:37:34.960 20466 20466 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:37:43.049 20466 20466 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:38:15.223 20130 20130 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:38:15.565 20130 20130 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:38:15.696 20130 20130 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:38:26.900 20130 20130 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:38:26.958 20130 20130 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:38:26.962 20130 20130 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:38:30.300 20130 20130 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:38:33.573 20130 20130 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:38:33.607 20130 20130 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:38:33.612 20130 20130 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:38:38.087 20130 20130 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:38:43.158 20130 20130 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
```

After this i wen't ahead, closed and force stopped the application again. And ran the command with other paramers as described:

```
01-15 21:42:01.742 12048 12128 E Surface : freeAllBuffers: 1 buffers were freed while being dequeued!
01-15 21:42:01.828 20475 20475 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:42:01.865  3703  4643 E AudioSystem-JNI: Command failed for android_media_AudioSystem_setParameters: -22
01-15 21:42:01.865  3703  4643 E AudioSystem-JNI: Command failed for android_media_AudioSystem_setParameters: -22
01-15 21:42:01.964 20475 20475 D Constants: StashUrl: 192.168.0.21:9999 => http://192.168.0.21:9999/graphql
01-15 21:42:02.010 20475 20475 E MainFragment: Exception in addCustomFilterRow
01-15 21:42:02.010 20475 20475 E MainFragment: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String  
01-15 21:42:02.010 20475 20475 E MainFragment:  at com.github.damontecres.stashapp.MainFragment$addCustomFilterRow$1.invokeSuspend(MainFragment.kt:291)
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)  
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
01-15 21:42:02.010 20475 20475 E MainFragment:  at com.github.damontecres.stashapp.MainFragment.addCustomFilterRow(MainFragment.kt:289)
01-15 21:42:02.010 20475 20475 E MainFragment:  at com.github.damontecres.stashapp.MainFragment.access$addCustomFilterRow(MainFragment.kt:49)
01-15 21:42:02.010 20475 20475 E MainFragment:  at com.github.damontecres.stashapp.MainFragment$fetchData$1$1.invokeSuspend(MainFragment.kt:241)
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)       
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
01-15 21:42:02.010 20475 20475 E MainFragment:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
01-15 21:42:02.010 20475 20475 E MainFragment:  at android.os.Handler.handleCallback(Handler.java:938)
01-15 21:42:02.010 20475 20475 E MainFragment:  at android.os.Handler.dispatchMessage(Handler.java:99)
01-15 21:42:02.010 20475 20475 E MainFragment:  at android.os.Looper.loop(Looper.java:223)
01-15 21:42:02.010 20475 20475 E MainFragment:  at android.app.ActivityThread.main(ActivityThread.java:7668)
01-15 21:42:02.010 20475 20475 E MainFragment:  at java.lang.reflect.Method.invoke(Native Method)
01-15 21:42:02.010 20475 20475 E MainFragment:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-15 21:42:02.010 20475 20475 E MainFragment:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-15 21:42:02.012 20475 20475 E MainFragment: Exception in addCustomFilterRow
01-15 21:42:02.012 20475 20475 E MainFragment: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String  
01-15 21:42:02.012 20475 20475 E MainFragment:  at com.github.damontecres.stashapp.MainFragment$addCustomFilterRow$1.invokeSuspend(MainFragment.kt:291)
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)  
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
01-15 21:42:02.012 20475 20475 E MainFragment:  at com.github.damontecres.stashapp.MainFragment.addCustomFilterRow(MainFragment.kt:289)
01-15 21:42:02.012 20475 20475 E MainFragment:  at com.github.damontecres.stashapp.MainFragment.access$addCustomFilterRow(MainFragment.kt:49)
01-15 21:42:02.012 20475 20475 E MainFragment:  at com.github.damontecres.stashapp.MainFragment$fetchData$1$1.invokeSuspend(MainFragment.kt:241)
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)       
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
01-15 21:42:02.012 20475 20475 E MainFragment:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
01-15 21:42:02.012 20475 20475 E MainFragment:  at android.os.Handler.handleCallback(Handler.java:938)
01-15 21:42:02.012 20475 20475 E MainFragment:  at android.os.Handler.dispatchMessage(Handler.java:99)
01-15 21:42:02.012 20475 20475 E MainFragment:  at android.os.Looper.loop(Looper.java:223)
01-15 21:42:02.012 20475 20475 E MainFragment:  at android.app.ActivityThread.main(ActivityThread.java:7668)
01-15 21:42:02.012 20475 20475 E MainFragment:  at java.lang.reflect.Method.invoke(Native Method)
01-15 21:42:02.012 20475 20475 E MainFragment:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-15 21:42:02.012 20475 20475 E MainFragment:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-15 21:42:05.356  3703  4483 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
```

The Full log of the `:E` output is very long. I attached only the section that i assume is important. However i can export it to a .txt and send it to you on discord. I think i found you user on the stash server.

**Comment by damontecres** [comment]
Thank you @st0r4ge! That gave me exactly the info I needed. #40 should fix this issue.

**Comment by damontecres** [comment]
Give [`v0.0.6`](https://github.com/damontecres/StashAppAndroidTV/releases/tag/v0.0.6) a shot and see if this issue is fixed!

**Comment by st0r4ge** [comment]
The screen now populates, however it does not seem to be matching the recently released scenes from the WebUi. In fact it's showing some older scenes with mixed dates.

So there might be an issue with sorting by release date.

For example, it shows the scenes in this order for me:
2022-12-16
2018-12-06
2023-09-16
2022-08-17
2023-11-16

**Comment by andrewmeyer** [comment]
I can confirm the same behavior @st0r4ge reports in 0.0.6:
- 2016
- 1016
- 2023
- 2016
- 2016

**Comment by damontecres** [comment]
This should finally be fix in https://github.com/damontecres/StashAppAndroidTV/releases/tag/v0.0.7!

**Comment by st0r4ge** [comment]
I can confirm this fixes the sorting issue on my installation. Many Thanks @damontecres  🙏
